/**
 * Seed script for Pantry Checker database.
 * Run: node supabase/seed.mjs
 * Requires: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY env vars
 */

import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

const CATEGORIES = [
  { slug: "dairy", icon: "🥛", es: "Lácteos", en: "Dairy" },
  { slug: "meat", icon: "🥩", es: "Carnes", en: "Meat" },
  { slug: "deli", icon: "🥓", es: "Embutidos", en: "Deli meats" },
  { slug: "fruits", icon: "🍎", es: "Frutas", en: "Fruits" },
  { slug: "vegetables", icon: "🥦", es: "Verduras", en: "Vegetables" },
  { slug: "sauces", icon: "🫙", es: "Salsas y condimentos", en: "Sauces & condiments" },
  { slug: "beverages", icon: "🥤", es: "Bebidas", en: "Beverages" },
  { slug: "grains", icon: "🌾", es: "Cereales y granos", en: "Grains & cereals" },
  { slug: "canned", icon: "🥫", es: "Conservas y enlatados", en: "Canned goods" },
  { slug: "bakery", icon: "🍞", es: "Panadería", en: "Bakery" },
  { slug: "frozen", icon: "🧊", es: "Congelados", en: "Frozen" },
  { slug: "snacks", icon: "🍿", es: "Snacks", en: "Snacks" },
  { slug: "oils", icon: "🫒", es: "Aceites y vinagres", en: "Oils & vinegars" },
  { slug: "baby-food", icon: "🍼", es: "Alimentación infantil", en: "Baby food" },
  { slug: "seafood", icon: "🐟", es: "Pescados y mariscos", en: "Seafood" },
  { slug: "eggs", icon: "🥚", es: "Huevos", en: "Eggs" },
  { slug: "nuts", icon: "🥜", es: "Frutos secos", en: "Nuts & dried fruits" },
  { slug: "spices", icon: "🌶️", es: "Especias y hierbas", en: "Spices & herbs" },
  { slug: "sweets", icon: "🍫", es: "Dulces y postres", en: "Sweets & desserts" },
  { slug: "pasta", icon: "🍝", es: "Pasta y arroces", en: "Pasta & rice" },
];

const PRODUCTS = [
  // DAIRY (dairy)
  { slug: "milk", cat: "dairy", opened: 5, unopened: 7, fridge: 7, freezer: 90, es: { name: "Leche", desc: "Leche de vaca pasteurizada.", tips: "Guardar siempre en nevera. No dejar fuera más de 2 horas.", spoil: "Olor agrio, grumos, sabor ácido." }, en: { name: "Milk", desc: "Pasteurized cow's milk.", tips: "Always keep refrigerated. Don't leave out for more than 2 hours.", spoil: "Sour smell, lumps, acidic taste." } },
  { slug: "yogurt", cat: "dairy", opened: 5, unopened: 21, fridge: 7, freezer: 60, es: { name: "Yogur", desc: "Yogur natural o de sabores.", tips: "Mantener en nevera. Consumir pronto una vez abierto.", spoil: "Moho en superficie, olor fuerte, textura líquida excesiva." }, en: { name: "Yogurt", desc: "Plain or flavored yogurt.", tips: "Keep refrigerated. Consume soon after opening.", spoil: "Mold on surface, strong odor, excessively liquid texture." } },
  { slug: "butter", cat: "dairy", opened: 30, unopened: 90, fridge: 30, freezer: 270, es: { name: "Mantequilla", desc: "Mantequilla de leche de vaca.", tips: "Guardar en nevera bien tapada. Se puede congelar.", spoil: "Color amarillo oscuro, olor rancio, sabor amargo." }, en: { name: "Butter", desc: "Cow's milk butter.", tips: "Keep refrigerated and well covered. Can be frozen.", spoil: "Dark yellow color, rancid smell, bitter taste." } },
  { slug: "cream-cheese", cat: "dairy", opened: 10, unopened: 30, fridge: 14, freezer: null, es: { name: "Queso crema", desc: "Queso crema tipo Philadelphia.", tips: "Mantener en nevera. No congelar.", spoil: "Moho, olor fuerte, textura seca." }, en: { name: "Cream cheese", desc: "Philadelphia-style cream cheese.", tips: "Keep refrigerated. Do not freeze.", spoil: "Mold, strong odor, dry texture." } },
  { slug: "grated-cheese", cat: "dairy", opened: 7, unopened: 60, fridge: 7, freezer: 180, es: { name: "Queso rallado", desc: "Queso rallado envasado.", tips: "Cerrar bien después de usar. Guardar en nevera.", spoil: "Moho, olor fuerte a amoníaco." }, en: { name: "Grated cheese", desc: "Packaged grated cheese.", tips: "Close tightly after use. Keep refrigerated.", spoil: "Mold, strong ammonia smell." } },
  { slug: "fresh-cheese", cat: "dairy", opened: 3, unopened: 14, fridge: 5, freezer: null, es: { name: "Queso fresco", desc: "Queso fresco tipo Burgos.", tips: "Consumir rápido una vez abierto. Mantener en nevera.", spoil: "Textura viscosa, olor agrio, moho." }, en: { name: "Fresh cheese", desc: "Fresh white cheese.", tips: "Consume quickly once opened. Keep refrigerated.", spoil: "Slimy texture, sour smell, mold." } },
  { slug: "cured-cheese", cat: "dairy", opened: 30, unopened: 180, fridge: 45, freezer: 180, es: { name: "Queso curado", desc: "Queso curado tipo manchego.", tips: "Envolver en papel film o encerado. Guardar en nevera.", spoil: "Moho excesivo (algo de moho es normal), textura reseca." }, en: { name: "Cured cheese", desc: "Cured cheese like manchego.", tips: "Wrap in cling film or wax paper. Keep refrigerated.", spoil: "Excessive mold (some mold is normal), dried-out texture." } },
  { slug: "whipping-cream", cat: "dairy", opened: 3, unopened: 21, fridge: 5, freezer: 90, es: { name: "Nata para montar", desc: "Nata líquida para montar.", tips: "Mantener en nevera. Usar rápido una vez abierta.", spoil: "Olor agrio, grumos, separación de líquidos." }, en: { name: "Whipping cream", desc: "Liquid whipping cream.", tips: "Keep refrigerated. Use quickly once opened.", spoil: "Sour smell, lumps, liquid separation." } },
  { slug: "sour-cream", cat: "dairy", opened: 14, unopened: 21, fridge: 14, freezer: null, es: { name: "Nata agria", desc: "Crema agria para cocinar.", tips: "Guardar en nevera bien cerrada.", spoil: "Moho, olor desagradable, separación excesiva." }, en: { name: "Sour cream", desc: "Sour cream for cooking.", tips: "Keep refrigerated and well sealed.", spoil: "Mold, unpleasant odor, excessive separation." } },
  { slug: "sliced-cheese", cat: "dairy", opened: 7, unopened: 30, fridge: 10, freezer: 180, es: { name: "Queso en lonchas", desc: "Queso en lonchas envasado.", tips: "Cerrar bien el envase. Guardar en nevera.", spoil: "Bordes secos, moho, olor fuerte." }, en: { name: "Sliced cheese", desc: "Packaged sliced cheese.", tips: "Close package tightly. Keep refrigerated.", spoil: "Dry edges, mold, strong smell." } },

  // MEAT (meat)
  { slug: "chicken-breast", cat: "meat", opened: 2, unopened: 3, fridge: 2, freezer: 270, es: { name: "Pechuga de pollo", desc: "Pechuga de pollo fresca.", tips: "Cocinar en 1-2 días. Guardar en la parte más fría de la nevera.", spoil: "Color grisáceo, olor fuerte, textura pegajosa." }, en: { name: "Chicken breast", desc: "Fresh chicken breast.", tips: "Cook within 1-2 days. Store in coldest part of fridge.", spoil: "Grayish color, strong odor, sticky texture." } },
  { slug: "ground-beef", cat: "meat", opened: 1, unopened: 2, fridge: 2, freezer: 120, es: { name: "Carne picada", desc: "Carne de ternera picada.", tips: "Consumir el mismo día o al siguiente. Cocinar bien.", spoil: "Color marrón oscuro, olor fuerte, textura pegajosa." }, en: { name: "Ground beef", desc: "Minced beef.", tips: "Consume same day or next. Cook thoroughly.", spoil: "Dark brown color, strong odor, sticky texture." } },
  { slug: "pork-chops", cat: "meat", opened: 2, unopened: 4, fridge: 3, freezer: 180, es: { name: "Chuletas de cerdo", desc: "Chuletas de cerdo frescas.", tips: "Mantener en nevera en envase cerrado.", spoil: "Olor desagradable, color grisáceo, textura viscosa." }, en: { name: "Pork chops", desc: "Fresh pork chops.", tips: "Keep refrigerated in sealed container.", spoil: "Unpleasant odor, grayish color, slimy texture." } },
  { slug: "beef-steak", cat: "meat", opened: 2, unopened: 5, fridge: 3, freezer: 180, es: { name: "Filete de ternera", desc: "Filete de ternera fresco.", tips: "Guardar en la parte baja de la nevera. Consumir pronto.", spoil: "Color verdoso, olor fuerte, superficie pegajosa." }, en: { name: "Beef steak", desc: "Fresh beef steak.", tips: "Store in bottom of fridge. Consume soon.", spoil: "Greenish color, strong odor, sticky surface." } },
  { slug: "lamb", cat: "meat", opened: 2, unopened: 4, fridge: 3, freezer: 180, es: { name: "Cordero", desc: "Carne de cordero fresca.", tips: "Mantener en nevera. Cocinar en 2-3 días.", spoil: "Olor fuerte a rancio, superficie viscosa." }, en: { name: "Lamb", desc: "Fresh lamb meat.", tips: "Keep refrigerated. Cook within 2-3 days.", spoil: "Strong rancid smell, slimy surface." } },
  { slug: "cooked-chicken", cat: "meat", opened: 3, unopened: 4, fridge: 4, freezer: 120, es: { name: "Pollo cocinado", desc: "Pollo ya cocinado (asado, hervido).", tips: "Guardar en recipiente cerrado en nevera.", spoil: "Olor agrio, textura viscosa, moho." }, en: { name: "Cooked chicken", desc: "Already cooked chicken (roasted, boiled).", tips: "Store in sealed container in fridge.", spoil: "Sour smell, slimy texture, mold." } },
  { slug: "turkey-breast", cat: "meat", opened: 2, unopened: 3, fridge: 2, freezer: 180, es: { name: "Pechuga de pavo", desc: "Pechuga de pavo fresca.", tips: "Cocinar en 1-2 días tras compra.", spoil: "Color grisáceo, olor fuerte, textura pegajosa." }, en: { name: "Turkey breast", desc: "Fresh turkey breast.", tips: "Cook within 1-2 days of purchase.", spoil: "Grayish color, strong odor, sticky texture." } },
  { slug: "rabbit", cat: "meat", opened: 2, unopened: 3, fridge: 2, freezer: 270, es: { name: "Conejo", desc: "Carne de conejo fresca.", tips: "Mantener en la parte más fría de la nevera.", spoil: "Olor desagradable, textura viscosa, decoloración." }, en: { name: "Rabbit", desc: "Fresh rabbit meat.", tips: "Keep in the coldest part of the fridge.", spoil: "Unpleasant odor, slimy texture, discoloration." } },

  // DELI (deli)
  { slug: "cooked-ham", cat: "deli", opened: 4, unopened: 14, fridge: 5, freezer: 60, es: { name: "Jamón cocido", desc: "Jamón york / jamón cocido en lonchas.", tips: "Cerrar bien el envase. Consumir en 3-5 días una vez abierto.", spoil: "Superficie viscosa, olor agrio, cambio de color." }, en: { name: "Cooked ham", desc: "Sliced cooked ham.", tips: "Close package tightly. Consume within 3-5 days once opened.", spoil: "Slimy surface, sour smell, color change." } },
  { slug: "serrano-ham", cat: "deli", opened: 21, unopened: 180, fridge: 30, freezer: 90, es: { name: "Jamón serrano", desc: "Jamón serrano curado.", tips: "Guardar cubierto con un paño. No necesita nevera si está entero.", spoil: "Moho excesivo, olor rancio, cristales de grasa amarillenta." }, en: { name: "Serrano ham", desc: "Cured serrano ham.", tips: "Keep covered with a cloth. Doesn't need fridge if whole.", spoil: "Excessive mold, rancid smell, yellow fat crystals." } },
  { slug: "chorizo", cat: "deli", opened: 14, unopened: 90, fridge: 21, freezer: 90, es: { name: "Chorizo", desc: "Chorizo curado español.", tips: "Guardar en lugar fresco y seco. En nevera una vez cortado.", spoil: "Moho no habitual, olor rancio, textura muy seca." }, en: { name: "Chorizo", desc: "Spanish cured chorizo.", tips: "Store in a cool, dry place. Refrigerate once cut.", spoil: "Unusual mold, rancid smell, very dry texture." } },
  { slug: "salami", cat: "deli", opened: 14, unopened: 60, fridge: 21, freezer: 60, es: { name: "Salami", desc: "Salami o salchichón curado.", tips: "Envolver bien en film. Guardar en nevera.", spoil: "Moho verde/negro, olor desagradable." }, en: { name: "Salami", desc: "Cured salami.", tips: "Wrap well in cling film. Keep refrigerated.", spoil: "Green/black mold, unpleasant odor." } },
  { slug: "turkey-deli", cat: "deli", opened: 3, unopened: 14, fridge: 5, freezer: 60, es: { name: "Pavo en lonchas", desc: "Fiambre de pavo en lonchas.", tips: "Consumir rápido una vez abierto. Guardar en nevera.", spoil: "Superficie viscosa, olor agrio." }, en: { name: "Sliced turkey", desc: "Sliced turkey deli meat.", tips: "Consume quickly once opened. Keep refrigerated.", spoil: "Slimy surface, sour smell." } },
  { slug: "bacon", cat: "deli", opened: 7, unopened: 14, fridge: 7, freezer: 30, es: { name: "Bacon", desc: "Bacon en lonchas.", tips: "Mantener en nevera. Cocinar antes de consumir.", spoil: "Color grisáceo, olor desagradable, textura pegajosa." }, en: { name: "Bacon", desc: "Sliced bacon.", tips: "Keep refrigerated. Cook before consuming.", spoil: "Grayish color, unpleasant odor, sticky texture." } },
  { slug: "mortadella", cat: "deli", opened: 5, unopened: 21, fridge: 7, freezer: 60, es: { name: "Mortadela", desc: "Mortadela en lonchas o pieza.", tips: "Guardar en nevera bien envuelta.", spoil: "Superficie viscosa, olor agrio, moho." }, en: { name: "Mortadella", desc: "Sliced or whole mortadella.", tips: "Keep refrigerated and well wrapped.", spoil: "Slimy surface, sour smell, mold." } },
  { slug: "fuet", cat: "deli", opened: 14, unopened: 90, fridge: 21, freezer: 60, es: { name: "Fuet", desc: "Fuet o longaniza curada.", tips: "Guardar en lugar fresco. En nevera una vez cortado.", spoil: "Moho no habitual, textura excesivamente seca." }, en: { name: "Fuet", desc: "Cured thin sausage.", tips: "Store in a cool place. Refrigerate once cut.", spoil: "Unusual mold, excessively dry texture." } },

  // FRUITS (fruits)
  { slug: "apple", cat: "fruits", opened: 5, unopened: 28, fridge: 28, freezer: 240, es: { name: "Manzana", desc: "Manzana fresca.", tips: "Guardar en nevera para mayor duración. Separar de otras frutas.", spoil: "Textura blanda, manchas marrones, arrugas." }, en: { name: "Apple", desc: "Fresh apple.", tips: "Refrigerate for longer shelf life. Keep separate from other fruits.", spoil: "Soft texture, brown spots, wrinkles." } },
  { slug: "banana", cat: "fruits", opened: 2, unopened: 5, fridge: 7, freezer: 180, es: { name: "Plátano", desc: "Plátano o banana.", tips: "No refrigerar si está verde. Congelar pelado para smoothies.", spoil: "Piel completamente negra, pulpa marrón, olor fermentado." }, en: { name: "Banana", desc: "Banana.", tips: "Don't refrigerate if unripe. Freeze peeled for smoothies.", spoil: "Completely black skin, brown flesh, fermented smell." } },
  { slug: "strawberries", cat: "fruits", opened: 2, unopened: 3, fridge: 5, freezer: 180, es: { name: "Fresas", desc: "Fresas frescas.", tips: "No lavar hasta consumir. Guardar en nevera.", spoil: "Moho, textura muy blanda, olor fermentado." }, en: { name: "Strawberries", desc: "Fresh strawberries.", tips: "Don't wash until ready to eat. Keep refrigerated.", spoil: "Mold, very soft texture, fermented smell." } },
  { slug: "orange", cat: "fruits", opened: 3, unopened: 14, fridge: 21, freezer: 180, es: { name: "Naranja", desc: "Naranja fresca.", tips: "A temperatura ambiente duran 1 semana. En nevera hasta 3.", spoil: "Moho, piel muy blanda, mal olor." }, en: { name: "Orange", desc: "Fresh orange.", tips: "Room temperature lasts 1 week. Refrigerated up to 3.", spoil: "Mold, very soft skin, bad smell." } },
  { slug: "lemon", cat: "fruits", opened: 5, unopened: 21, fridge: 28, freezer: 120, es: { name: "Limón", desc: "Limón fresco.", tips: "Guardar en nevera en bolsa cerrada.", spoil: "Piel arrugada, moho, textura muy blanda." }, en: { name: "Lemon", desc: "Fresh lemon.", tips: "Keep in fridge in a sealed bag.", spoil: "Wrinkled skin, mold, very soft texture." } },
  { slug: "avocado", cat: "fruits", opened: 2, unopened: 5, fridge: 3, freezer: 120, es: { name: "Aguacate", desc: "Aguacate fresco.", tips: "Rociar con limón una vez cortado. Guardar con hueso.", spoil: "Interior marrón oscuro, olor rancio, textura fibrosa." }, en: { name: "Avocado", desc: "Fresh avocado.", tips: "Sprinkle with lemon once cut. Store with pit.", spoil: "Dark brown interior, rancid smell, fibrous texture." } },
  { slug: "grapes", cat: "fruits", opened: 3, unopened: 7, fridge: 7, freezer: 180, es: { name: "Uvas", desc: "Uvas frescas.", tips: "No lavar hasta consumir. Guardar en nevera.", spoil: "Moho, uvas blandas y arrugadas, olor a vinagre." }, en: { name: "Grapes", desc: "Fresh grapes.", tips: "Don't wash until ready to eat. Keep refrigerated.", spoil: "Mold, soft and wrinkled grapes, vinegar smell." } },
  { slug: "watermelon", cat: "fruits", opened: 3, unopened: 14, fridge: 5, freezer: 180, es: { name: "Sandía", desc: "Sandía fresca.", tips: "Una vez cortada, cubrir con film y refrigerar.", spoil: "Textura arenosa, olor fermentado, color apagado." }, en: { name: "Watermelon", desc: "Fresh watermelon.", tips: "Once cut, cover with cling film and refrigerate.", spoil: "Grainy texture, fermented smell, dull color." } },
  { slug: "melon", cat: "fruits", opened: 3, unopened: 10, fridge: 5, freezer: 180, es: { name: "Melón", desc: "Melón fresco.", tips: "Refrigerar una vez cortado. Cubrir con film.", spoil: "Textura blanda, olor fermentado, moho." }, en: { name: "Melon", desc: "Fresh melon.", tips: "Refrigerate once cut. Cover with cling film.", spoil: "Soft texture, fermented smell, mold." } },
  { slug: "pear", cat: "fruits", opened: 3, unopened: 7, fridge: 10, freezer: 180, es: { name: "Pera", desc: "Pera fresca.", tips: "Madurar a temperatura ambiente, luego refrigerar.", spoil: "Textura muy blanda, manchas marrones, olor fermentado." }, en: { name: "Pear", desc: "Fresh pear.", tips: "Ripen at room temperature, then refrigerate.", spoil: "Very soft texture, brown spots, fermented smell." } },

  // VEGETABLES (vegetables)
  { slug: "tomato", cat: "vegetables", opened: 3, unopened: 7, fridge: 10, freezer: 180, es: { name: "Tomate", desc: "Tomate fresco.", tips: "Mejor a temperatura ambiente para mantener sabor. Refrigerar si está muy maduro.", spoil: "Moho, textura muy blanda, grietas, olor a fermentado." }, en: { name: "Tomato", desc: "Fresh tomato.", tips: "Best at room temperature for flavor. Refrigerate if very ripe.", spoil: "Mold, very soft texture, cracks, fermented smell." } },
  { slug: "lettuce", cat: "vegetables", opened: 3, unopened: 7, fridge: 7, freezer: null, es: { name: "Lechuga", desc: "Lechuga fresca (iceberg, romana, etc.).", tips: "Envolver en papel de cocina húmedo. No congelar.", spoil: "Hojas marrones, textura viscosa, olor desagradable." }, en: { name: "Lettuce", desc: "Fresh lettuce (iceberg, romaine, etc.).", tips: "Wrap in damp paper towel. Do not freeze.", spoil: "Brown leaves, slimy texture, unpleasant odor." } },
  { slug: "onion", cat: "vegetables", opened: 7, unopened: 60, fridge: 10, freezer: 180, es: { name: "Cebolla", desc: "Cebolla fresca.", tips: "Entera en lugar fresco y oscuro. Cortada en nevera en recipiente cerrado.", spoil: "Textura blanda, brotes, moho, olor fuerte." }, en: { name: "Onion", desc: "Fresh onion.", tips: "Whole in a cool, dark place. Cut in fridge in sealed container.", spoil: "Soft texture, sprouts, mold, strong smell." } },
  { slug: "potato", cat: "vegetables", opened: 5, unopened: 60, fridge: null, freezer: 180, es: { name: "Patata", desc: "Patata fresca.", tips: "Guardar en lugar fresco, oscuro y seco. NO refrigerar crudas.", spoil: "Color verde, brotes largos, textura blanda, olor dulzón." }, en: { name: "Potato", desc: "Fresh potato.", tips: "Store in cool, dark, dry place. Do NOT refrigerate raw.", spoil: "Green color, long sprouts, soft texture, sweet smell." } },
  { slug: "carrot", cat: "vegetables", opened: 5, unopened: 21, fridge: 21, freezer: 300, es: { name: "Zanahoria", desc: "Zanahoria fresca.", tips: "Quitar las hojas verdes. Guardar en nevera en bolsa.", spoil: "Textura blanda y flexible, manchas negras, viscosidad." }, en: { name: "Carrot", desc: "Fresh carrot.", tips: "Remove green tops. Store in fridge in a bag.", spoil: "Soft and bendy texture, black spots, sliminess." } },
  { slug: "pepper", cat: "vegetables", opened: 4, unopened: 10, fridge: 10, freezer: 180, es: { name: "Pimiento", desc: "Pimiento fresco (verde, rojo, amarillo).", tips: "Guardar en nevera. Cortar y congelar para cocinar.", spoil: "Arrugas, textura blanda, moho, manchas oscuras." }, en: { name: "Bell pepper", desc: "Fresh bell pepper (green, red, yellow).", tips: "Keep refrigerated. Cut and freeze for cooking.", spoil: "Wrinkles, soft texture, mold, dark spots." } },
  { slug: "cucumber", cat: "vegetables", opened: 3, unopened: 7, fridge: 7, freezer: null, es: { name: "Pepino", desc: "Pepino fresco.", tips: "Guardar en nevera. Envolver en papel si está cortado.", spoil: "Textura blanda, interior acuoso, moho." }, en: { name: "Cucumber", desc: "Fresh cucumber.", tips: "Keep refrigerated. Wrap in paper if cut.", spoil: "Soft texture, watery interior, mold." } },
  { slug: "spinach", cat: "vegetables", opened: 2, unopened: 5, fridge: 5, freezer: 300, es: { name: "Espinacas", desc: "Espinacas frescas.", tips: "Guardar en nevera sin lavar. Lavar antes de usar.", spoil: "Hojas oscuras y viscosas, olor fuerte." }, en: { name: "Spinach", desc: "Fresh spinach.", tips: "Store in fridge unwashed. Wash before use.", spoil: "Dark and slimy leaves, strong odor." } },
  { slug: "mushrooms", cat: "vegetables", opened: 3, unopened: 7, fridge: 7, freezer: 300, es: { name: "Champiñones", desc: "Champiñones frescos.", tips: "Guardar en bolsa de papel en nevera. No usar bolsa de plástico.", spoil: "Textura viscosa, manchas oscuras, olor fuerte." }, en: { name: "Mushrooms", desc: "Fresh mushrooms.", tips: "Store in paper bag in fridge. Don't use plastic bag.", spoil: "Slimy texture, dark spots, strong odor." } },
  { slug: "broccoli", cat: "vegetables", opened: 3, unopened: 5, fridge: 5, freezer: 300, es: { name: "Brócoli", desc: "Brócoli fresco.", tips: "No lavar hasta usar. Guardar en nevera.", spoil: "Color amarillento, olor fuerte, textura blanda." }, en: { name: "Broccoli", desc: "Fresh broccoli.", tips: "Don't wash until ready to use. Keep refrigerated.", spoil: "Yellowish color, strong odor, soft texture." } },
  { slug: "zucchini", cat: "vegetables", opened: 4, unopened: 10, fridge: 10, freezer: 180, es: { name: "Calabacín", desc: "Calabacín fresco.", tips: "Guardar en nevera en cajón de verduras.", spoil: "Textura blanda, manchas oscuras, interior acuoso." }, en: { name: "Zucchini", desc: "Fresh zucchini.", tips: "Store in fridge vegetable drawer.", spoil: "Soft texture, dark spots, watery interior." } },
  { slug: "garlic", cat: "vegetables", opened: 7, unopened: 90, fridge: null, freezer: 180, es: { name: "Ajo", desc: "Cabeza de ajo.", tips: "Guardar en lugar fresco y seco. No refrigerar entero.", spoil: "Brotes verdes, textura blanda, manchas de moho." }, en: { name: "Garlic", desc: "Garlic head.", tips: "Store in cool, dry place. Don't refrigerate whole.", spoil: "Green sprouts, soft texture, mold spots." } },

  // SAUCES (sauces)
  { slug: "mayonnaise", cat: "sauces", opened: 60, unopened: 180, fridge: 60, freezer: null, es: { name: "Mayonesa", desc: "Mayonesa comercial envasada.", tips: "Siempre en nevera una vez abierta. Usar cubiertos limpios.", spoil: "Olor ácido, separación de aceite, cambio de color." }, en: { name: "Mayonnaise", desc: "Commercial packaged mayonnaise.", tips: "Always refrigerate once opened. Use clean utensils.", spoil: "Acidic smell, oil separation, color change." } },
  { slug: "ketchup", cat: "sauces", opened: 180, unopened: 365, fridge: 180, freezer: null, es: { name: "Ketchup", desc: "Ketchup comercial.", tips: "Guardar en nevera una vez abierto. Larga duración.", spoil: "Separación de líquido, color oscuro, olor a vinagre fuerte." }, en: { name: "Ketchup", desc: "Commercial ketchup.", tips: "Refrigerate once opened. Long shelf life.", spoil: "Liquid separation, dark color, strong vinegar smell." } },
  { slug: "mustard", cat: "sauces", opened: 365, unopened: 730, fridge: 365, freezer: null, es: { name: "Mostaza", desc: "Mostaza comercial.", tips: "Guardar en nevera. Duración muy larga.", spoil: "Color apagado, textura seca, olor débil." }, en: { name: "Mustard", desc: "Commercial mustard.", tips: "Keep refrigerated. Very long shelf life.", spoil: "Dull color, dry texture, weak smell." } },
  { slug: "tomato-sauce", cat: "sauces", opened: 5, unopened: 365, fridge: 7, freezer: 90, es: { name: "Tomate frito", desc: "Salsa de tomate frito en bote.", tips: "Pasar a recipiente de vidrio una vez abierto. Guardar en nevera.", spoil: "Moho, olor agrio, burbujas, cambio de color." }, en: { name: "Tomato sauce", desc: "Bottled tomato sauce.", tips: "Transfer to glass container once opened. Refrigerate.", spoil: "Mold, sour smell, bubbles, color change." } },
  { slug: "soy-sauce", cat: "sauces", opened: 180, unopened: 1095, fridge: 365, freezer: null, es: { name: "Salsa de soja", desc: "Salsa de soja.", tips: "Guardar en nevera una vez abierta. Muy larga duración.", spoil: "Cambio de color significativo, olor desagradable." }, en: { name: "Soy sauce", desc: "Soy sauce.", tips: "Refrigerate once opened. Very long shelf life.", spoil: "Significant color change, unpleasant odor." } },
  { slug: "hot-sauce", cat: "sauces", opened: 180, unopened: 1095, fridge: 180, freezer: null, es: { name: "Salsa picante", desc: "Salsa picante tipo Tabasco.", tips: "Guardar en nevera para mantener sabor.", spoil: "Cambio de color, pérdida de picor, olor extraño." }, en: { name: "Hot sauce", desc: "Hot sauce like Tabasco.", tips: "Refrigerate to maintain flavor.", spoil: "Color change, loss of heat, strange smell." } },
  { slug: "pesto", cat: "sauces", opened: 5, unopened: 180, fridge: 7, freezer: 90, es: { name: "Pesto", desc: "Salsa pesto (albahaca, piñones, parmesano).", tips: "Cubrir con aceite de oliva para conservar. Guardar en nevera.", spoil: "Cambio de color a marrón, olor rancio, moho." }, en: { name: "Pesto", desc: "Pesto sauce (basil, pine nuts, parmesan).", tips: "Cover with olive oil to preserve. Keep refrigerated.", spoil: "Color change to brown, rancid smell, mold." } },
  { slug: "bbq-sauce", cat: "sauces", opened: 120, unopened: 365, fridge: 120, freezer: null, es: { name: "Salsa barbacoa", desc: "Salsa barbacoa comercial.", tips: "Guardar en nevera una vez abierta.", spoil: "Separación de líquidos, moho, olor fuerte." }, en: { name: "BBQ sauce", desc: "Commercial BBQ sauce.", tips: "Refrigerate once opened.", spoil: "Liquid separation, mold, strong odor." } },
  { slug: "olive-oil", cat: "oils", opened: 180, unopened: 730, fridge: null, freezer: null, es: { name: "Aceite de oliva", desc: "Aceite de oliva virgen extra.", tips: "Guardar en lugar fresco y oscuro. Cerrar bien la botella.", spoil: "Olor y sabor rancio, color apagado." }, en: { name: "Olive oil", desc: "Extra virgin olive oil.", tips: "Store in cool, dark place. Close bottle tightly.", spoil: "Rancid smell and taste, dull color." } },
  { slug: "vinegar", cat: "oils", opened: 730, unopened: 1825, fridge: null, freezer: null, es: { name: "Vinagre", desc: "Vinagre de vino o manzana.", tips: "Guardar en lugar fresco. Duración prácticamente indefinida.", spoil: "Es difícil que se estropee. Puede formar 'madre' (inofensiva)." }, en: { name: "Vinegar", desc: "Wine or apple vinegar.", tips: "Store in cool place. Practically indefinite shelf life.", spoil: "Hard to go bad. May form 'mother' (harmless)." } },

  // BEVERAGES (beverages)
  { slug: "orange-juice", cat: "beverages", opened: 5, unopened: 14, fridge: 7, freezer: 120, es: { name: "Zumo de naranja", desc: "Zumo de naranja natural o envasado.", tips: "Guardar en nevera. El natural consumir en 2-3 días.", spoil: "Olor a fermentado, sabor ácido, burbujas." }, en: { name: "Orange juice", desc: "Fresh or packaged orange juice.", tips: "Keep refrigerated. Fresh juice consume in 2-3 days.", spoil: "Fermented smell, acidic taste, bubbles." } },
  { slug: "wine", cat: "beverages", opened: 3, unopened: 1825, fridge: 5, freezer: null, es: { name: "Vino", desc: "Vino tinto, blanco o rosado.", tips: "Una vez abierto, tapar y guardar en nevera. Tinto 3-5 días, blanco 2-3.", spoil: "Sabor avinagrado, olor a moho, color apagado." }, en: { name: "Wine", desc: "Red, white, or rosé wine.", tips: "Once opened, cork and refrigerate. Red 3-5 days, white 2-3.", spoil: "Vinegary taste, musty smell, dull color." } },
  { slug: "beer", cat: "beverages", opened: 1, unopened: 180, fridge: 1, freezer: null, es: { name: "Cerveza", desc: "Cerveza en botella o lata.", tips: "Consumir una vez abierta. No re-enfriar.", spoil: "Sabor plano, olor a cartón, turbidez." }, en: { name: "Beer", desc: "Bottled or canned beer.", tips: "Consume once opened. Don't re-chill.", spoil: "Flat taste, cardboard smell, cloudiness." } },
  { slug: "coffee-ground", cat: "beverages", opened: 14, unopened: 180, fridge: 30, freezer: 150, es: { name: "Café molido", desc: "Café molido envasado.", tips: "Guardar en recipiente hermético. Lugar fresco y oscuro.", spoil: "Pérdida de aroma, sabor plano, olor a rancio." }, en: { name: "Ground coffee", desc: "Packaged ground coffee.", tips: "Store in airtight container. Cool, dark place.", spoil: "Loss of aroma, flat taste, rancid smell." } },
  { slug: "tea", cat: "beverages", opened: 180, unopened: 730, fridge: null, freezer: null, es: { name: "Té", desc: "Té en bolsitas o a granel.", tips: "Guardar en lugar seco y oscuro. Recipiente hermético.", spoil: "Pérdida de aroma y sabor. Moho si hay humedad." }, en: { name: "Tea", desc: "Tea bags or loose leaf.", tips: "Store in dry, dark place. Airtight container.", spoil: "Loss of aroma and flavor. Mold if damp." } },
  { slug: "soft-drinks", cat: "beverages", opened: 1, unopened: 180, fridge: 3, freezer: null, es: { name: "Refresco", desc: "Refrescos carbonatados (cola, limonada, etc.).", tips: "Consumir el mismo día una vez abierto. Pierde gas rápido.", spoil: "Sin burbujas, sabor plano, color alterado." }, en: { name: "Soft drink", desc: "Carbonated soft drinks (cola, lemonade, etc.).", tips: "Consume same day once opened. Loses carbonation fast.", spoil: "No bubbles, flat taste, altered color." } },

  // GRAINS (grains)
  { slug: "bread-white", cat: "bakery", opened: 3, unopened: 5, fridge: 7, freezer: 90, es: { name: "Pan blanco", desc: "Pan blanco de barra o molde.", tips: "Guardar en bolsa cerrada. Congelar en rebanadas.", spoil: "Moho, textura dura, olor a humedad." }, en: { name: "White bread", desc: "White bread loaf or baguette.", tips: "Keep in sealed bag. Freeze in slices.", spoil: "Mold, hard texture, musty smell." } },
  { slug: "bread-whole", cat: "bakery", opened: 3, unopened: 5, fridge: 7, freezer: 90, es: { name: "Pan integral", desc: "Pan integral de molde.", tips: "Guardar en bolsa cerrada. Se congela bien.", spoil: "Moho, textura seca, olor a humedad." }, en: { name: "Whole wheat bread", desc: "Whole wheat bread loaf.", tips: "Keep in sealed bag. Freezes well.", spoil: "Mold, dry texture, musty smell." } },
  { slug: "rice-cooked", cat: "pasta", opened: 1, unopened: null, fridge: 4, freezer: 180, es: { name: "Arroz cocido", desc: "Arroz ya cocinado.", tips: "Refrigerar en menos de 1 hora. Recalentar bien.", spoil: "Olor agrio, textura pegajosa, moho." }, en: { name: "Cooked rice", desc: "Already cooked rice.", tips: "Refrigerate within 1 hour. Reheat thoroughly.", spoil: "Sour smell, sticky texture, mold." } },
  { slug: "pasta-cooked", cat: "pasta", opened: 1, unopened: null, fridge: 5, freezer: 180, es: { name: "Pasta cocida", desc: "Pasta ya cocinada.", tips: "Guardar en recipiente cerrado en nevera. Añadir aceite para que no se pegue.", spoil: "Olor agrio, textura viscosa, moho." }, en: { name: "Cooked pasta", desc: "Already cooked pasta.", tips: "Store in sealed container in fridge. Add oil to prevent sticking.", spoil: "Sour smell, slimy texture, mold." } },
  { slug: "rice-dry", cat: "pasta", opened: 365, unopened: 730, fridge: null, freezer: null, es: { name: "Arroz seco", desc: "Arroz crudo sin cocinar.", tips: "Guardar en recipiente hermético en lugar seco.", spoil: "Insectos, olor extraño, moho." }, en: { name: "Dry rice", desc: "Raw uncooked rice.", tips: "Store in airtight container in dry place.", spoil: "Insects, strange smell, mold." } },
  { slug: "pasta-dry", cat: "pasta", opened: 365, unopened: 730, fridge: null, freezer: null, es: { name: "Pasta seca", desc: "Pasta cruda sin cocinar.", tips: "Cerrar bien el paquete. Guardar en lugar seco.", spoil: "Insectos, textura extraña, moho." }, en: { name: "Dry pasta", desc: "Raw uncooked pasta.", tips: "Close package tightly. Store in dry place.", spoil: "Insects, strange texture, mold." } },
  { slug: "oats", cat: "grains", opened: 180, unopened: 365, fridge: null, freezer: null, es: { name: "Avena", desc: "Copos de avena.", tips: "Guardar en recipiente hermético en lugar seco.", spoil: "Olor rancio, insectos, cambio de color." }, en: { name: "Oats", desc: "Oat flakes.", tips: "Store in airtight container in dry place.", spoil: "Rancid smell, insects, color change." } },
  { slug: "cereal", cat: "grains", opened: 60, unopened: 240, fridge: null, freezer: null, es: { name: "Cereales de desayuno", desc: "Cereales de desayuno tipo corn flakes.", tips: "Cerrar bien la bolsa interior. Lugar seco.", spoil: "Textura blanda (pierden crujiente), olor rancio." }, en: { name: "Breakfast cereal", desc: "Breakfast cereals like corn flakes.", tips: "Close inner bag tightly. Dry place.", spoil: "Soft texture (lose crunch), rancid smell." } },
  { slug: "flour", cat: "grains", opened: 180, unopened: 365, fridge: null, freezer: 730, es: { name: "Harina", desc: "Harina de trigo.", tips: "Guardar en recipiente hermético. Lugar fresco y seco.", spoil: "Insectos, olor rancio, grumos, moho." }, en: { name: "Flour", desc: "Wheat flour.", tips: "Store in airtight container. Cool, dry place.", spoil: "Insects, rancid smell, lumps, mold." } },

  // CANNED (canned)
  { slug: "canned-tuna", cat: "canned", opened: 2, unopened: 1825, fridge: 3, freezer: null, es: { name: "Atún en lata", desc: "Atún en conserva.", tips: "Una vez abierto, pasar a recipiente de vidrio. No guardar en la lata.", spoil: "Olor fuerte, color oscuro, textura viscosa." }, en: { name: "Canned tuna", desc: "Canned tuna.", tips: "Once opened, transfer to glass container. Don't store in can.", spoil: "Strong odor, dark color, slimy texture." } },
  { slug: "canned-beans", cat: "canned", opened: 3, unopened: 1095, fridge: 5, freezer: 180, es: { name: "Alubias en lata", desc: "Alubias o frijoles en conserva.", tips: "Pasar a recipiente de vidrio una vez abierto.", spoil: "Olor agrio, moho, textura viscosa." }, en: { name: "Canned beans", desc: "Canned beans.", tips: "Transfer to glass container once opened.", spoil: "Sour smell, mold, slimy texture." } },
  { slug: "canned-corn", cat: "canned", opened: 3, unopened: 1095, fridge: 4, freezer: 180, es: { name: "Maíz en lata", desc: "Maíz dulce en conserva.", tips: "Pasar a recipiente cerrado una vez abierto.", spoil: "Olor agrio, textura blanda, moho." }, en: { name: "Canned corn", desc: "Canned sweet corn.", tips: "Transfer to sealed container once opened.", spoil: "Sour smell, soft texture, mold." } },
  { slug: "canned-tomatoes", cat: "canned", opened: 3, unopened: 1095, fridge: 5, freezer: 90, es: { name: "Tomate en lata", desc: "Tomate triturado o pelado en lata.", tips: "No guardar en la lata abierta. Pasar a vidrio.", spoil: "Olor ácido fuerte, moho, burbujas." }, en: { name: "Canned tomatoes", desc: "Crushed or peeled canned tomatoes.", tips: "Don't store in opened can. Transfer to glass.", spoil: "Strong acidic smell, mold, bubbles." } },
  { slug: "canned-sardines", cat: "canned", opened: 1, unopened: 1825, fridge: 2, freezer: null, es: { name: "Sardinas en lata", desc: "Sardinas en conserva.", tips: "Consumir rápido una vez abierto. Pasar a recipiente.", spoil: "Olor muy fuerte, textura viscosa." }, en: { name: "Canned sardines", desc: "Canned sardines.", tips: "Consume quickly once opened. Transfer to container.", spoil: "Very strong odor, slimy texture." } },
  { slug: "canned-chickpeas", cat: "canned", opened: 3, unopened: 1095, fridge: 4, freezer: 180, es: { name: "Garbanzos en lata", desc: "Garbanzos en conserva.", tips: "Escurrir y pasar a recipiente cerrado.", spoil: "Olor agrio, textura viscosa, espuma." }, en: { name: "Canned chickpeas", desc: "Canned chickpeas.", tips: "Drain and transfer to sealed container.", spoil: "Sour smell, slimy texture, foam." } },

  // EGGS (eggs)
  { slug: "eggs", cat: "eggs", opened: null, unopened: 28, fridge: 35, freezer: 365, es: { name: "Huevos", desc: "Huevos frescos de gallina.", tips: "Guardar en nevera. No lavar hasta usar. Comprobar frescura con agua.", spoil: "Flotan en agua, olor a azufre al abrir, clara acuosa." }, en: { name: "Eggs", desc: "Fresh chicken eggs.", tips: "Keep refrigerated. Don't wash until use. Check freshness with water test.", spoil: "Float in water, sulfur smell when opened, watery white." } },
  { slug: "hard-boiled-egg", cat: "eggs", opened: 1, unopened: 5, fridge: 7, freezer: null, es: { name: "Huevo cocido", desc: "Huevo duro cocido.", tips: "Con cáscara dura más. Guardar en nevera.", spoil: "Olor a azufre fuerte, textura gomosa, decoloración." }, en: { name: "Hard-boiled egg", desc: "Hard-boiled egg.", tips: "Lasts longer with shell on. Keep refrigerated.", spoil: "Strong sulfur smell, rubbery texture, discoloration." } },

  // SEAFOOD (seafood)
  { slug: "fresh-salmon", cat: "seafood", opened: 1, unopened: 2, fridge: 2, freezer: 90, es: { name: "Salmón fresco", desc: "Salmón fresco en filetes.", tips: "Cocinar el mismo día o al siguiente. Guardar en parte fría de la nevera.", spoil: "Olor fuerte a pescado, textura viscosa, color apagado." }, en: { name: "Fresh salmon", desc: "Fresh salmon fillets.", tips: "Cook same day or next. Store in coldest part of fridge.", spoil: "Strong fishy smell, slimy texture, dull color." } },
  { slug: "fresh-shrimp", cat: "seafood", opened: 1, unopened: 2, fridge: 2, freezer: 180, es: { name: "Gambas frescas", desc: "Gambas o langostinos frescos.", tips: "Consumir el mismo día. Guardar sobre hielo en nevera.", spoil: "Olor a amoníaco, textura viscosa, cabeza oscura." }, en: { name: "Fresh shrimp", desc: "Fresh shrimp or prawns.", tips: "Consume same day. Store on ice in fridge.", spoil: "Ammonia smell, slimy texture, dark head." } },
  { slug: "smoked-salmon", cat: "seafood", opened: 3, unopened: 14, fridge: 5, freezer: 60, es: { name: "Salmón ahumado", desc: "Salmón ahumado en lonchas.", tips: "Cerrar bien el envase. Guardar en nevera.", spoil: "Olor muy fuerte, textura viscosa, cambio de color." }, en: { name: "Smoked salmon", desc: "Sliced smoked salmon.", tips: "Close package tightly. Keep refrigerated.", spoil: "Very strong smell, slimy texture, color change." } },
  { slug: "canned-anchovies", cat: "seafood", opened: 7, unopened: 365, fridge: 14, freezer: null, es: { name: "Anchoas en aceite", desc: "Anchoas en aceite de oliva.", tips: "Mantener cubiertas de aceite en nevera.", spoil: "Textura muy blanda, olor desagradable." }, en: { name: "Anchovies in oil", desc: "Anchovies in olive oil.", tips: "Keep covered in oil in fridge.", spoil: "Very soft texture, unpleasant odor." } },
  { slug: "frozen-fish", cat: "seafood", opened: null, unopened: null, fridge: 2, freezer: 180, es: { name: "Pescado congelado", desc: "Pescado congelado (merluza, bacalao, etc.).", tips: "Descongelar en nevera, nunca a temperatura ambiente.", spoil: "Cristales de hielo excesivos, color amarillento, olor fuerte." }, en: { name: "Frozen fish", desc: "Frozen fish (hake, cod, etc.).", tips: "Thaw in fridge, never at room temperature.", spoil: "Excessive ice crystals, yellowish color, strong smell." } },

  // BABY FOOD (baby-food)
  { slug: "baby-formula", cat: "baby-food", opened: 1, unopened: 365, fridge: null, freezer: null, es: { name: "Leche de fórmula", desc: "Leche de fórmula infantil preparada.", tips: "Usar dentro de 1 hora una vez preparada. En polvo: 30 días abierto.", spoil: "Olor agrio, grumos, separación." }, en: { name: "Baby formula", desc: "Prepared infant formula.", tips: "Use within 1 hour once prepared. Powder: 30 days opened.", spoil: "Sour smell, lumps, separation." } },
  { slug: "baby-puree", cat: "baby-food", opened: 1, unopened: 365, fridge: 2, freezer: 90, es: { name: "Potito / puré bebé", desc: "Puré de frutas o verduras para bebé.", tips: "No dar directamente del bote (la saliva contamina). Pasar a un plato.", spoil: "Moho, olor agrio, cambio de color, tapa hinchada." }, en: { name: "Baby purée", desc: "Fruit or vegetable baby purée.", tips: "Don't feed directly from jar (saliva contaminates). Transfer to a dish.", spoil: "Mold, sour smell, color change, swollen lid." } },

  // NUTS (nuts)
  { slug: "almonds", cat: "nuts", opened: 90, unopened: 365, fridge: 180, freezer: 365, es: { name: "Almendras", desc: "Almendras crudas o tostadas.", tips: "Guardar en recipiente hermético en lugar fresco.", spoil: "Sabor amargo, olor rancio." }, en: { name: "Almonds", desc: "Raw or roasted almonds.", tips: "Store in airtight container in cool place.", spoil: "Bitter taste, rancid smell." } },
  { slug: "walnuts", cat: "nuts", opened: 60, unopened: 180, fridge: 180, freezer: 365, es: { name: "Nueces", desc: "Nueces con o sin cáscara.", tips: "Con cáscara duran más. Guardar en lugar fresco.", spoil: "Sabor amargo y rancio, textura gomosa." }, en: { name: "Walnuts", desc: "Walnuts shelled or unshelled.", tips: "Last longer in shell. Store in cool place.", spoil: "Bitter and rancid taste, rubbery texture." } },
  { slug: "peanuts", cat: "nuts", opened: 90, unopened: 270, fridge: 180, freezer: 365, es: { name: "Cacahuetes", desc: "Cacahuetes tostados o crudos.", tips: "Guardar en recipiente hermético.", spoil: "Olor y sabor rancio, textura blanda." }, en: { name: "Peanuts", desc: "Roasted or raw peanuts.", tips: "Store in airtight container.", spoil: "Rancid smell and taste, soft texture." } },
  { slug: "peanut-butter", cat: "nuts", opened: 90, unopened: 365, fridge: 180, freezer: null, es: { name: "Mantequilla de cacahuete", desc: "Crema o mantequilla de cacahuete.", tips: "Natural: en nevera. Comercial: despensa vale.", spoil: "Olor rancio, separación excesiva de aceite, sabor amargo." }, en: { name: "Peanut butter", desc: "Peanut butter.", tips: "Natural: refrigerate. Commercial: pantry is fine.", spoil: "Rancid smell, excessive oil separation, bitter taste." } },
  { slug: "dried-fruits", cat: "nuts", opened: 30, unopened: 180, fridge: 180, freezer: 365, es: { name: "Frutas deshidratadas", desc: "Pasas, orejones, dátiles, etc.", tips: "Guardar en recipiente hermético en lugar fresco.", spoil: "Textura muy dura, moho, olor fermentado." }, en: { name: "Dried fruits", desc: "Raisins, dried apricots, dates, etc.", tips: "Store in airtight container in cool place.", spoil: "Very hard texture, mold, fermented smell." } },

  // SPICES (spices)
  { slug: "ground-pepper", cat: "spices", opened: 180, unopened: 1095, fridge: null, freezer: null, es: { name: "Pimienta molida", desc: "Pimienta negra molida.", tips: "Guardar en recipiente cerrado lejos de la luz.", spoil: "Pérdida total de aroma y picor." }, en: { name: "Ground pepper", desc: "Ground black pepper.", tips: "Store in sealed container away from light.", spoil: "Complete loss of aroma and heat." } },
  { slug: "salt", cat: "spices", opened: null, unopened: null, fridge: null, freezer: null, es: { name: "Sal", desc: "Sal de mesa o marina.", tips: "Guardar en lugar seco. Duración prácticamente indefinida.", spoil: "No se estropea. Puede apelmazarse con humedad." }, en: { name: "Salt", desc: "Table or sea salt.", tips: "Store in dry place. Practically indefinite shelf life.", spoil: "Doesn't go bad. May clump with moisture." } },
  { slug: "sugar", cat: "spices", opened: null, unopened: null, fridge: null, freezer: null, es: { name: "Azúcar", desc: "Azúcar blanca o morena.", tips: "Guardar en recipiente hermético. Duración indefinida.", spoil: "No se estropea. Puede formar grumos con humedad." }, en: { name: "Sugar", desc: "White or brown sugar.", tips: "Store in airtight container. Indefinite shelf life.", spoil: "Doesn't go bad. May form lumps with moisture." } },
  { slug: "cinnamon", cat: "spices", opened: 180, unopened: 1095, fridge: null, freezer: null, es: { name: "Canela", desc: "Canela en polvo o en rama.", tips: "En rama dura más. Guardar en recipiente cerrado.", spoil: "Pérdida de aroma, color apagado." }, en: { name: "Cinnamon", desc: "Ground or stick cinnamon.", tips: "Sticks last longer. Store in sealed container.", spoil: "Loss of aroma, dull color." } },
  { slug: "dried-oregano", cat: "spices", opened: 180, unopened: 1095, fridge: null, freezer: null, es: { name: "Orégano seco", desc: "Orégano seco en hojas.", tips: "Guardar en recipiente hermético lejos de la luz.", spoil: "Pérdida de aroma y color." }, en: { name: "Dried oregano", desc: "Dried oregano leaves.", tips: "Store in airtight container away from light.", spoil: "Loss of aroma and color." } },
  { slug: "fresh-basil", cat: "spices", opened: 3, unopened: 5, fridge: 7, freezer: 180, es: { name: "Albahaca fresca", desc: "Hojas de albahaca fresca.", tips: "Poner en vaso con agua como flores. No refrigerar si es posible.", spoil: "Hojas negras, textura viscosa, olor fuerte." }, en: { name: "Fresh basil", desc: "Fresh basil leaves.", tips: "Place in glass of water like flowers. Don't refrigerate if possible.", spoil: "Black leaves, slimy texture, strong odor." } },
  { slug: "fresh-parsley", cat: "spices", opened: 5, unopened: 7, fridge: 10, freezer: 180, es: { name: "Perejil fresco", desc: "Perejil fresco en rama.", tips: "Envolver en papel húmedo en nevera. O poner en agua.", spoil: "Hojas amarillas, textura blanda, moho." }, en: { name: "Fresh parsley", desc: "Fresh parsley bunch.", tips: "Wrap in damp paper in fridge. Or place in water.", spoil: "Yellow leaves, soft texture, mold." } },

  // SWEETS (sweets)
  { slug: "chocolate", cat: "sweets", opened: 120, unopened: 365, fridge: 240, freezer: 365, es: { name: "Chocolate", desc: "Tableta de chocolate.", tips: "Guardar en lugar fresco y seco. El bloom blanco es inofensivo.", spoil: "Bloom excesivo, olor rancio, textura arenosa." }, en: { name: "Chocolate", desc: "Chocolate bar.", tips: "Store in cool, dry place. White bloom is harmless.", spoil: "Excessive bloom, rancid smell, grainy texture." } },
  { slug: "jam", cat: "sweets", opened: 30, unopened: 365, fridge: 60, freezer: null, es: { name: "Mermelada", desc: "Mermelada de frutas.", tips: "Guardar en nevera una vez abierta. Usar cubiertos limpios.", spoil: "Moho en superficie, olor fermentado, cambio de color." }, en: { name: "Jam", desc: "Fruit jam.", tips: "Refrigerate once opened. Use clean utensils.", spoil: "Mold on surface, fermented smell, color change." } },
  { slug: "honey", cat: "sweets", opened: null, unopened: null, fridge: null, freezer: null, es: { name: "Miel", desc: "Miel natural de abeja.", tips: "Guardar a temperatura ambiente. Si cristaliza, calentar al baño maría.", spoil: "No se estropea. La cristalización es normal." }, en: { name: "Honey", desc: "Natural bee honey.", tips: "Store at room temperature. If crystallized, warm in water bath.", spoil: "Doesn't go bad. Crystallization is normal." } },
  { slug: "nutella", cat: "sweets", opened: 30, unopened: 365, fridge: null, freezer: null, es: { name: "Crema de cacao", desc: "Crema de cacao y avellanas tipo Nutella.", tips: "Guardar a temperatura ambiente. No refrigerar (se endurece).", spoil: "Olor rancio, textura seca, sabor amargo." }, en: { name: "Chocolate spread", desc: "Chocolate hazelnut spread like Nutella.", tips: "Store at room temperature. Don't refrigerate (hardens).", spoil: "Rancid smell, dry texture, bitter taste." } },
  { slug: "cookies", cat: "sweets", opened: 7, unopened: 60, fridge: null, freezer: 120, es: { name: "Galletas", desc: "Galletas envasadas.", tips: "Cerrar bien el paquete. Guardar en lugar seco.", spoil: "Textura blanda (pierden crujiente), olor rancio, moho." }, en: { name: "Cookies", desc: "Packaged cookies.", tips: "Close package tightly. Store in dry place.", spoil: "Soft texture (lose crunch), rancid smell, mold." } },
  { slug: "ice-cream", cat: "sweets", opened: 60, unopened: 120, fridge: null, freezer: 120, es: { name: "Helado", desc: "Helado en tarrina.", tips: "Poner film sobre la superficie antes de tapar para evitar cristales.", spoil: "Cristales de hielo excesivos, textura arenosa, sabor extraño." }, en: { name: "Ice cream", desc: "Ice cream tub.", tips: "Place cling film on surface before covering to prevent crystals.", spoil: "Excessive ice crystals, grainy texture, strange taste." } },

  // FROZEN (frozen)
  { slug: "frozen-vegetables", cat: "frozen", opened: 60, unopened: 300, fridge: 2, freezer: 300, es: { name: "Verduras congeladas", desc: "Mix de verduras congeladas.", tips: "No recongelar. Cocinar directamente sin descongelar.", spoil: "Cristales de hielo excesivos, decoloración, olor extraño." }, en: { name: "Frozen vegetables", desc: "Frozen vegetable mix.", tips: "Don't refreeze. Cook directly without thawing.", spoil: "Excessive ice crystals, discoloration, strange smell." } },
  { slug: "frozen-pizza", cat: "frozen", opened: null, unopened: null, fridge: 2, freezer: 180, es: { name: "Pizza congelada", desc: "Pizza congelada preparada.", tips: "No descongelar y recongelar. Hornear directamente.", spoil: "Quemadura por congelación, cristales de hielo, textura alterada." }, en: { name: "Frozen pizza", desc: "Frozen prepared pizza.", tips: "Don't thaw and refreeze. Bake directly.", spoil: "Freezer burn, ice crystals, altered texture." } },
  { slug: "frozen-fries", cat: "frozen", opened: 60, unopened: 240, fridge: null, freezer: 240, es: { name: "Patatas fritas congeladas", desc: "Patatas fritas precocinadas congeladas.", tips: "No recongelar. Freír u hornear directamente.", spoil: "Quemadura por congelación, textura blanda, decoloración." }, en: { name: "Frozen fries", desc: "Frozen pre-cooked french fries.", tips: "Don't refreeze. Fry or bake directly.", spoil: "Freezer burn, soft texture, discoloration." } },

  // SNACKS (snacks)
  { slug: "potato-chips", cat: "snacks", opened: 3, unopened: 60, fridge: null, freezer: null, es: { name: "Patatas fritas (bolsa)", desc: "Patatas fritas de bolsa.", tips: "Cerrar con pinza. Pierden crujiente rápido.", spoil: "Textura blanda, olor rancio, sabor a cartón." }, en: { name: "Potato chips", desc: "Bagged potato chips.", tips: "Close with clip. Lose crunch quickly.", spoil: "Soft texture, rancid smell, cardboard taste." } },
  { slug: "crackers", cat: "snacks", opened: 14, unopened: 180, fridge: null, freezer: null, es: { name: "Crackers", desc: "Crackers o galletas saladas.", tips: "Guardar en recipiente hermético.", spoil: "Textura blanda, olor rancio." }, en: { name: "Crackers", desc: "Crackers or saltine biscuits.", tips: "Store in airtight container.", spoil: "Soft texture, rancid smell." } },
  { slug: "popcorn", cat: "snacks", opened: 1, unopened: 180, fridge: null, freezer: null, es: { name: "Palomitas", desc: "Palomitas de maíz preparadas.", tips: "Consumir el mismo día. Guardar en recipiente cerrado.", spoil: "Textura blanda, sabor a rancio." }, en: { name: "Popcorn", desc: "Prepared popcorn.", tips: "Consume same day. Store in sealed container.", spoil: "Soft texture, rancid taste." } },
  { slug: "trail-mix", cat: "snacks", opened: 30, unopened: 180, fridge: 90, freezer: null, es: { name: "Mix de frutos secos", desc: "Mezcla de frutos secos y deshidratados.", tips: "Guardar en recipiente hermético.", spoil: "Olor rancio, sabor amargo, textura blanda." }, en: { name: "Trail mix", desc: "Mixed nuts and dried fruits.", tips: "Store in airtight container.", spoil: "Rancid smell, bitter taste, soft texture." } },

  // More DAIRY
  { slug: "condensed-milk", cat: "dairy", opened: 14, unopened: 365, fridge: 14, freezer: null, es: { name: "Leche condensada", desc: "Leche condensada azucarada.", tips: "Pasar a recipiente cerrado en nevera una vez abierto.", spoil: "Color amarillo oscuro, olor rancio, textura granulosa." }, en: { name: "Condensed milk", desc: "Sweetened condensed milk.", tips: "Transfer to sealed container in fridge once opened.", spoil: "Dark yellow color, rancid smell, grainy texture." } },
  { slug: "evaporated-milk", cat: "dairy", opened: 3, unopened: 365, fridge: 5, freezer: null, es: { name: "Leche evaporada", desc: "Leche evaporada en lata.", tips: "Pasar a recipiente de vidrio una vez abierto. Guardar en nevera.", spoil: "Olor agrio, grumos, cambio de color." }, en: { name: "Evaporated milk", desc: "Canned evaporated milk.", tips: "Transfer to glass container once opened. Refrigerate.", spoil: "Sour smell, lumps, color change." } },
  { slug: "plant-milk", cat: "dairy", opened: 5, unopened: 180, fridge: 7, freezer: null, es: { name: "Leche vegetal", desc: "Leche de avena, soja, almendras, etc.", tips: "Agitar antes de servir. Guardar en nevera una vez abierta.", spoil: "Olor agrio, grumos, separación, sabor amargo." }, en: { name: "Plant milk", desc: "Oat, soy, almond milk, etc.", tips: "Shake before serving. Refrigerate once opened.", spoil: "Sour smell, lumps, separation, bitter taste." } },

  // More SAUCES
  { slug: "worcestershire", cat: "sauces", opened: 365, unopened: 1825, fridge: null, freezer: null, es: { name: "Salsa Worcestershire", desc: "Salsa inglesa Worcestershire.", tips: "Guardar en lugar fresco. Larga duración.", spoil: "Difícil que se estropee. Cambio de sabor tras mucho tiempo." }, en: { name: "Worcestershire sauce", desc: "Worcestershire sauce.", tips: "Store in cool place. Long shelf life.", spoil: "Hard to go bad. Flavor change after long time." } },
  { slug: "hummus", cat: "sauces", opened: 4, unopened: 14, fridge: 7, freezer: 120, es: { name: "Hummus", desc: "Hummus de garbanzos.", tips: "Mantener en nevera. Rociar con aceite para conservar.", spoil: "Olor agrio, moho, sabor ácido." }, en: { name: "Hummus", desc: "Chickpea hummus.", tips: "Keep refrigerated. Drizzle with oil to preserve.", spoil: "Sour smell, mold, acidic taste." } },
  { slug: "guacamole", cat: "sauces", opened: 1, unopened: 5, fridge: 2, freezer: 90, es: { name: "Guacamole", desc: "Guacamole fresco o envasado.", tips: "Cubrir con film en contacto. Añadir limón para evitar oxidación.", spoil: "Color marrón oscuro, olor rancio, sabor amargo." }, en: { name: "Guacamole", desc: "Fresh or packaged guacamole.", tips: "Cover with cling film in contact. Add lemon to prevent oxidation.", spoil: "Dark brown color, rancid smell, bitter taste." } },

  // More BAKERY
  { slug: "tortillas-flour", cat: "bakery", opened: 5, unopened: 30, fridge: 14, freezer: 180, es: { name: "Tortillas de harina", desc: "Tortillas de trigo para wraps.", tips: "Cerrar bien el paquete. Se congelan muy bien.", spoil: "Moho, textura rígida, olor a humedad." }, en: { name: "Flour tortillas", desc: "Wheat tortillas for wraps.", tips: "Close package tightly. Freeze very well.", spoil: "Mold, rigid texture, musty smell." } },
  { slug: "croissants", cat: "bakery", opened: 2, unopened: 3, fridge: 5, freezer: 60, es: { name: "Croissants", desc: "Croissants de mantequilla.", tips: "Congelar si no se van a consumir pronto. Recalentar en horno.", spoil: "Moho, textura dura y seca, olor a rancio." }, en: { name: "Croissants", desc: "Butter croissants.", tips: "Freeze if not consuming soon. Reheat in oven.", spoil: "Mold, hard and dry texture, rancid smell." } },
  { slug: "pizza-dough", cat: "bakery", opened: 2, unopened: 7, fridge: 3, freezer: 90, es: { name: "Masa de pizza", desc: "Masa de pizza refrigerada.", tips: "Usar dentro de 2-3 días de abrirla.", spoil: "Olor a levadura fuerte, color grisáceo, textura pegajosa." }, en: { name: "Pizza dough", desc: "Refrigerated pizza dough.", tips: "Use within 2-3 days of opening.", spoil: "Strong yeast smell, grayish color, sticky texture." } },

  // More VEGETABLES
  { slug: "sweet-potato", cat: "vegetables", opened: 5, unopened: 30, fridge: 7, freezer: 180, es: { name: "Boniato", desc: "Boniato o batata.", tips: "Crudo: lugar fresco y oscuro. Cocinado: nevera.", spoil: "Textura blanda, brotes, manchas oscuras, olor dulzón." }, en: { name: "Sweet potato", desc: "Sweet potato.", tips: "Raw: cool, dark place. Cooked: fridge.", spoil: "Soft texture, sprouts, dark spots, sweet smell." } },
  { slug: "corn-on-cob", cat: "vegetables", opened: 2, unopened: 3, fridge: 3, freezer: 240, es: { name: "Mazorca de maíz", desc: "Maíz fresco en mazorca.", tips: "Guardar con hojas en nevera. Cocinar pronto.", spoil: "Granos oscuros, olor desagradable, textura seca." }, en: { name: "Corn on the cob", desc: "Fresh corn on the cob.", tips: "Store with husks in fridge. Cook soon.", spoil: "Dark kernels, unpleasant smell, dry texture." } },
  { slug: "celery", cat: "vegetables", opened: 7, unopened: 14, fridge: 14, freezer: 180, es: { name: "Apio", desc: "Tallo de apio fresco.", tips: "Envolver en papel de aluminio en nevera.", spoil: "Textura blanda y flexible, color amarillento." }, en: { name: "Celery", desc: "Fresh celery stalk.", tips: "Wrap in aluminum foil in fridge.", spoil: "Soft and bendy texture, yellowish color." } },
  { slug: "cabbage", cat: "vegetables", opened: 5, unopened: 14, fridge: 14, freezer: 180, es: { name: "Repollo", desc: "Repollo o col.", tips: "Guardar en nevera en bolsa. Cortado dura menos.", spoil: "Hojas marrones, olor fuerte a azufre, textura viscosa." }, en: { name: "Cabbage", desc: "Cabbage.", tips: "Store in fridge in bag. Cut lasts less.", spoil: "Brown leaves, strong sulfur smell, slimy texture." } },
  { slug: "eggplant", cat: "vegetables", opened: 3, unopened: 7, fridge: 7, freezer: 180, es: { name: "Berenjena", desc: "Berenjena fresca.", tips: "No refrigerar a menos de 10°C. Usar pronto.", spoil: "Textura blanda, manchas marrones, semillas oscuras." }, en: { name: "Eggplant", desc: "Fresh eggplant.", tips: "Don't refrigerate below 10°C. Use soon.", spoil: "Soft texture, brown spots, dark seeds." } },
  { slug: "green-beans", cat: "vegetables", opened: 3, unopened: 5, fridge: 5, freezer: 240, es: { name: "Judías verdes", desc: "Judías verdes frescas.", tips: "Guardar en nevera sin lavar.", spoil: "Textura blanda, manchas marrones, viscosidad." }, en: { name: "Green beans", desc: "Fresh green beans.", tips: "Store in fridge unwashed.", spoil: "Soft texture, brown spots, sliminess." } },
  { slug: "asparagus", cat: "vegetables", opened: 2, unopened: 3, fridge: 5, freezer: 240, es: { name: "Espárragos", desc: "Espárragos frescos.", tips: "Poner en vaso con agua en nevera como flores.", spoil: "Puntas oscuras y blandas, olor fuerte." }, en: { name: "Asparagus", desc: "Fresh asparagus.", tips: "Place in glass of water in fridge like flowers.", spoil: "Dark and soft tips, strong odor." } },
  { slug: "peas", cat: "vegetables", opened: 2, unopened: 3, fridge: 3, freezer: 300, es: { name: "Guisantes frescos", desc: "Guisantes frescos sin vaina.", tips: "Consumir rápido o congelar.", spoil: "Color amarillento, textura dura, olor fuerte." }, en: { name: "Fresh peas", desc: "Fresh shelled peas.", tips: "Consume quickly or freeze.", spoil: "Yellowish color, hard texture, strong odor." } },
  { slug: "artichoke", cat: "vegetables", opened: 3, unopened: 7, fridge: 7, freezer: 180, es: { name: "Alcachofa", desc: "Alcachofa fresca.", tips: "Guardar en nevera. Rociar con limón una vez cortada.", spoil: "Hojas marrones abiertas, textura seca, olor fuerte." }, en: { name: "Artichoke", desc: "Fresh artichoke.", tips: "Keep refrigerated. Sprinkle with lemon once cut.", spoil: "Open brown leaves, dry texture, strong odor." } },
  { slug: "leek", cat: "vegetables", opened: 5, unopened: 10, fridge: 10, freezer: 180, es: { name: "Puerro", desc: "Puerro fresco.", tips: "Guardar en nevera en bolsa.", spoil: "Textura viscosa, hojas amarillas, olor fuerte." }, en: { name: "Leek", desc: "Fresh leek.", tips: "Store in fridge in bag.", spoil: "Slimy texture, yellow leaves, strong odor." } },
  { slug: "cauliflower", cat: "vegetables", opened: 3, unopened: 7, fridge: 7, freezer: 240, es: { name: "Coliflor", desc: "Coliflor fresca.", tips: "Guardar en nevera. No lavar hasta usar.", spoil: "Manchas marrones, olor a azufre fuerte, textura blanda." }, en: { name: "Cauliflower", desc: "Fresh cauliflower.", tips: "Keep refrigerated. Don't wash until use.", spoil: "Brown spots, strong sulfur smell, soft texture." } },

  // More MEAT / leftovers
  { slug: "cooked-stew", cat: "meat", opened: null, unopened: null, fridge: 4, freezer: 90, es: { name: "Guiso cocinado", desc: "Guiso o estofado ya preparado.", tips: "Enfriar rápido y guardar en nevera. Recalentar bien.", spoil: "Olor agrio, moho en superficie, textura viscosa." }, en: { name: "Cooked stew", desc: "Prepared stew.", tips: "Cool quickly and refrigerate. Reheat thoroughly.", spoil: "Sour smell, mold on surface, slimy texture." } },
  { slug: "soup", cat: "meat", opened: null, unopened: null, fridge: 4, freezer: 90, es: { name: "Sopa casera", desc: "Sopa o caldo casero.", tips: "Enfriar rápido. Guardar en recipientes pequeños.", spoil: "Olor agrio, burbujas, moho, sabor ácido." }, en: { name: "Homemade soup", desc: "Homemade soup or broth.", tips: "Cool quickly. Store in small containers.", spoil: "Sour smell, bubbles, mold, acidic taste." } },

  // More canned
  { slug: "canned-olives", cat: "canned", opened: 7, unopened: 730, fridge: 14, freezer: null, es: { name: "Aceitunas en bote", desc: "Aceitunas en conserva.", tips: "Mantener cubiertas de líquido en nevera.", spoil: "Textura muy blanda, olor desagradable, moho." }, en: { name: "Canned olives", desc: "Canned olives.", tips: "Keep covered in liquid in fridge.", spoil: "Very soft texture, unpleasant odor, mold." } },
  { slug: "canned-peaches", cat: "canned", opened: 5, unopened: 730, fridge: 7, freezer: null, es: { name: "Melocotón en almíbar", desc: "Melocotón en conserva con almíbar.", tips: "Pasar a recipiente de vidrio con su almíbar.", spoil: "Olor fermentado, textura muy blanda, moho." }, en: { name: "Canned peaches", desc: "Canned peaches in syrup.", tips: "Transfer to glass container with syrup.", spoil: "Fermented smell, very soft texture, mold." } },
  { slug: "canned-pineapple", cat: "canned", opened: 5, unopened: 730, fridge: 7, freezer: null, es: { name: "Piña en lata", desc: "Piña en almíbar o en su jugo.", tips: "Pasar a recipiente de vidrio una vez abierto.", spoil: "Olor fermentado, textura descompuesta." }, en: { name: "Canned pineapple", desc: "Canned pineapple in syrup or juice.", tips: "Transfer to glass container once opened.", spoil: "Fermented smell, mushy texture." } },

  // More beverages
  { slug: "coconut-water", cat: "beverages", opened: 1, unopened: 365, fridge: 2, freezer: null, es: { name: "Agua de coco", desc: "Agua de coco envasada.", tips: "Consumir el mismo día una vez abierta.", spoil: "Olor agrio, sabor ácido, turbidez." }, en: { name: "Coconut water", desc: "Packaged coconut water.", tips: "Consume same day once opened.", spoil: "Sour smell, acidic taste, cloudiness." } },
  { slug: "aloe-vera-juice", cat: "beverages", opened: 7, unopened: 365, fridge: 10, freezer: null, es: { name: "Zumo de aloe vera", desc: "Zumo o bebida de aloe vera.", tips: "Guardar en nevera una vez abierto.", spoil: "Olor desagradable, cambio de color, sabor amargo." }, en: { name: "Aloe vera juice", desc: "Aloe vera juice or drink.", tips: "Refrigerate once opened.", spoil: "Unpleasant smell, color change, bitter taste." } },

  // Additional products to reach ~200
  { slug: "mozzarella", cat: "dairy", opened: 3, unopened: 21, fridge: 5, freezer: 180, es: { name: "Mozzarella", desc: "Queso mozzarella fresco.", tips: "Mantener en su líquido en nevera.", spoil: "Textura viscosa, olor agrio, moho." }, en: { name: "Mozzarella", desc: "Fresh mozzarella cheese.", tips: "Keep in its liquid in fridge.", spoil: "Slimy texture, sour smell, mold." } },
  { slug: "parmesan", cat: "dairy", opened: 60, unopened: 365, fridge: 60, freezer: 365, es: { name: "Parmesano", desc: "Queso parmesano en bloque o rallado.", tips: "En bloque: envolver en papel encerado. Rallado: nevera cerrado.", spoil: "Moho en exceso, olor a amoníaco fuerte." }, en: { name: "Parmesan", desc: "Block or grated parmesan cheese.", tips: "Block: wrap in wax paper. Grated: sealed in fridge.", spoil: "Excessive mold, strong ammonia smell." } },
  { slug: "ricotta", cat: "dairy", opened: 5, unopened: 14, fridge: 7, freezer: null, es: { name: "Ricotta", desc: "Queso ricotta fresco.", tips: "Consumir rápido una vez abierto.", spoil: "Moho, olor agrio, textura acuosa." }, en: { name: "Ricotta", desc: "Fresh ricotta cheese.", tips: "Consume quickly once opened.", spoil: "Mold, sour smell, watery texture." } },
  { slug: "tofu", cat: "dairy", opened: 3, unopened: 21, fridge: 5, freezer: 150, es: { name: "Tofu", desc: "Tofu firme o sedoso.", tips: "Sumergir en agua limpia y cambiar a diario.", spoil: "Olor agrio, textura viscosa, color amarillento." }, en: { name: "Tofu", desc: "Firm or silken tofu.", tips: "Submerge in clean water and change daily.", spoil: "Sour smell, slimy texture, yellowish color." } },
  { slug: "sausages-fresh", cat: "meat", opened: 2, unopened: 3, fridge: 3, freezer: 60, es: { name: "Salchichas frescas", desc: "Salchichas frescas de carnicería.", tips: "Cocinar en 2-3 días tras compra.", spoil: "Color grisáceo, olor fuerte, textura viscosa." }, en: { name: "Fresh sausages", desc: "Fresh butcher sausages.", tips: "Cook within 2-3 days of purchase.", spoil: "Grayish color, strong odor, slimy texture." } },
  { slug: "frankfurters", cat: "meat", opened: 7, unopened: 30, fridge: 7, freezer: 60, es: { name: "Salchichas Frankfurt", desc: "Salchichas tipo Frankfurt envasadas.", tips: "Guardar en su líquido en nevera.", spoil: "Textura viscosa, olor agrio, cambio de color." }, en: { name: "Frankfurters", desc: "Packaged frankfurter sausages.", tips: "Keep in their liquid in fridge.", spoil: "Slimy texture, sour smell, color change." } },
  { slug: "mango", cat: "fruits", opened: 3, unopened: 7, fridge: 5, freezer: 180, es: { name: "Mango", desc: "Mango fresco.", tips: "Madurar a temperatura ambiente. Refrigerar cuando esté maduro.", spoil: "Textura muy blanda, olor fermentado, manchas negras grandes." }, en: { name: "Mango", desc: "Fresh mango.", tips: "Ripen at room temperature. Refrigerate when ripe.", spoil: "Very soft texture, fermented smell, large black spots." } },
  { slug: "pineapple", cat: "fruits", opened: 3, unopened: 5, fridge: 5, freezer: 180, es: { name: "Piña fresca", desc: "Piña fresca entera o cortada.", tips: "Cortada: guardar en recipiente cerrado en nevera.", spoil: "Olor a fermentado, textura muy blanda, moho." }, en: { name: "Fresh pineapple", desc: "Fresh whole or cut pineapple.", tips: "Cut: store in sealed container in fridge.", spoil: "Fermented smell, very soft texture, mold." } },
  { slug: "kiwi", cat: "fruits", opened: 3, unopened: 7, fridge: 14, freezer: 180, es: { name: "Kiwi", desc: "Kiwi fresco.", tips: "Madurar fuera de la nevera. Refrigerar cuando esté maduro.", spoil: "Textura muy blanda, olor fermentado, moho." }, en: { name: "Kiwi", desc: "Fresh kiwi.", tips: "Ripen outside fridge. Refrigerate when ripe.", spoil: "Very soft texture, fermented smell, mold." } },
  { slug: "blueberries", cat: "fruits", opened: 3, unopened: 5, fridge: 7, freezer: 300, es: { name: "Arándanos", desc: "Arándanos frescos.", tips: "No lavar hasta consumir. Guardar en nevera.", spoil: "Moho, textura muy blanda, jugo excesivo." }, en: { name: "Blueberries", desc: "Fresh blueberries.", tips: "Don't wash until ready to eat. Keep refrigerated.", spoil: "Mold, very soft texture, excessive juice." } },
  { slug: "peach", cat: "fruits", opened: 2, unopened: 5, fridge: 5, freezer: 180, es: { name: "Melocotón fresco", desc: "Melocotón o nectarina fresca.", tips: "Madurar a temperatura ambiente. Refrigerar cuando maduro.", spoil: "Textura muy blanda, manchas marrones, moho, olor fermentado." }, en: { name: "Fresh peach", desc: "Fresh peach or nectarine.", tips: "Ripen at room temperature. Refrigerate when ripe.", spoil: "Very soft texture, brown spots, mold, fermented smell." } },
  { slug: "cherry", cat: "fruits", opened: 3, unopened: 5, fridge: 7, freezer: 300, es: { name: "Cerezas", desc: "Cerezas frescas.", tips: "No lavar hasta consumir. Guardar en nevera.", spoil: "Textura blanda, moho, manchas oscuras." }, en: { name: "Cherries", desc: "Fresh cherries.", tips: "Don't wash until ready to eat. Keep refrigerated.", spoil: "Soft texture, mold, dark spots." } },
  { slug: "fig", cat: "fruits", opened: 1, unopened: 3, fridge: 3, freezer: 180, es: { name: "Higos", desc: "Higos frescos.", tips: "Muy perecederos. Consumir pronto. Guardar en nevera.", spoil: "Textura muy blanda, moho, olor fermentado." }, en: { name: "Figs", desc: "Fresh figs.", tips: "Very perishable. Consume soon. Keep refrigerated.", spoil: "Very soft texture, mold, fermented smell." } },
  { slug: "pomegranate", cat: "fruits", opened: 5, unopened: 21, fridge: 14, freezer: 365, es: { name: "Granada", desc: "Granada fresca.", tips: "Entera dura semanas. Los granos: nevera en recipiente cerrado.", spoil: "Granos marrones, olor fermentado, piel excesivamente arrugada." }, en: { name: "Pomegranate", desc: "Fresh pomegranate.", tips: "Whole lasts weeks. Seeds: fridge in sealed container.", spoil: "Brown seeds, fermented smell, excessively wrinkled skin." } },
];

async function seed() {
  console.log("Seeding categories...");

  // Insert categories
  for (const cat of CATEGORIES) {
    const { data: catData, error: catError } = await supabase
      .from("categories")
      .upsert({ slug: cat.slug, icon: cat.icon }, { onConflict: "slug" })
      .select()
      .single();

    if (catError) {
      console.error(`Error inserting category ${cat.slug}:`, catError.message);
      continue;
    }

    // Insert translations
    for (const locale of ["es", "en"]) {
      await supabase.from("category_translations").upsert(
        {
          category_id: catData.id,
          locale,
          name: cat[locale],
        },
        { onConflict: "category_id,locale" }
      );
    }
  }

  console.log(`Seeded ${CATEGORIES.length} categories.`);
  console.log("Seeding products...");

  // Get category map
  const { data: cats } = await supabase.from("categories").select("id, slug");
  const catMap = Object.fromEntries(cats.map((c) => [c.slug, c.id]));

  let count = 0;
  for (const prod of PRODUCTS) {
    const { data: prodData, error: prodError } = await supabase
      .from("products")
      .upsert(
        {
          slug: prod.slug,
          category_id: catMap[prod.cat] ?? null,
          opened_duration_days: prod.opened,
          unopened_duration_days: prod.unopened,
          fridge_duration_days: prod.fridge,
          freezer_duration_days: prod.freezer,
        },
        { onConflict: "slug" }
      )
      .select()
      .single();

    if (prodError) {
      console.error(`Error inserting product ${prod.slug}:`, prodError.message);
      continue;
    }

    // Insert translations
    for (const locale of ["es", "en"]) {
      const t = prod[locale];
      await supabase.from("product_translations").upsert(
        {
          product_id: prodData.id,
          locale,
          name: t.name,
          description: t.desc,
          storage_tips: t.tips,
          signs_of_spoilage: t.spoil,
        },
        { onConflict: "product_id,locale" }
      );
    }

    count++;
  }

  console.log(`Seeded ${count} products.`);
  console.log("Done!");
}

seed().catch(console.error);
